### ISSUE TITLE
Config flow could not be loaded: 500: Internal Server Error when clicking configured 

### ISSUE THREAD

**Issue by nquick** [xannor/ha_reolink_discovery#4]
Hi, 

After a recent update I've lost access to my cameras in HA. When I click Configure in the add-on it comes up with the error Config flow could not be loaded: 500: Internal Server Error

I have tried re-installing the add-on unsuccessfully. 

I've updated my NVR to the latest firmware version

**Comment by xannor** [comment]
Currently no other integration takes advantage of this integration, so it should not be having an effect on your access to your NVR. I would recommend removing this and using the built in supported ReoLink integration, as I have been working with the maintainer of that one going forward. This is mostly left here for reference.

**Comment by radekgosciniak** [comment]
I have the same on new HA installation

**Comment by JakkeQ** [comment]
Same here, I removed the integration from my device and downloaded again. This did not help.

**Comment by seemedFilm** [comment]
same

**Comment by xannor** [comment]
As I stated in the readme, and above, this is just a helper integration, that was only used by my discontinued reolink integration, no other integration uses this, so having it installed will do nothing other than cause headaches. The "official" integration already uses dhcp detection so it does not need this, and I have no plans to take this any further at this time, I again reccomend removing this integration and just using one of the other reolink integrations.
